// Guards against src/workers/generated/*.ts drifting from data/framework and
// data/focus (T-037). Those two files are committed (typecheck needs them
// to exist as real modules — see src/workers/data.ts) but are generated by
// `node scripts/bundle-worker-data.mjs`; this test re-derives the same
// shapes straight from the committed data/ directories (via the same
// ajv-validating loaders the bundler uses) and asserts a byte-for-byte
// structural match, so a data/ change without a re-run of the bundler
// fails CI instead of silently shipping stale worker data.
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { loadArtifact, loadFocusStore } from "../shared/index.js";
import frameworkArtifact from "./generated/framework-artifact.js";
import focusStoreData from "./generated/focus-store.js";

const FRAMEWORK_DIR = join(import.meta.dirname, "../../data/framework");
const FOCUS_DIR = join(import.meta.dirname, "../../data/focus");

describe("generated worker data (T-037)", () => {
  it("framework-artifact.ts matches a fresh load of data/framework", () => {
    expect(frameworkArtifact).toEqual(loadArtifact(FRAMEWORK_DIR));
  });

  it("focus-store.ts matches a fresh load of data/focus", () => {
    const fresh = loadFocusStore(FOCUS_DIR);
    expect(focusStoreData).toEqual({
      index: fresh.index,
      versions: Object.fromEntries(fresh.versions),
      diff: fresh.diff,
      kpiMapping: fresh.kpiMapping,
      sampleManifest: fresh.sampleManifest,
      sampleCsv: Object.fromEntries(fresh.sampleCsv),
    });
  });
});
