import fs from "node:fs";
import path from "node:path";
import type { ApprovalsPolicy } from "./config.js";
import { CliError, ensureDir, readTextIfExists } from "./util.js";

export const GENERATED_HEADER = "GENERATED by `agentic approvals compile` — edit approvals.yaml instead.";

// ---------------------------------------------------------------------------
// Pure compilers: policy -> file content (exported for snapshot-style tests)
// ---------------------------------------------------------------------------

const FORCE_PUSH_PATTERNS = ["Bash(git push --force*)", "Bash(git push -f*)"];

/**
 * Derive the full ask/deny permission lists from the policy:
 * - force_push: never -> deny force-push patterns; human -> ask them.
 * - merge_to_main / deploy_production / release: human -> ask their commands.
 * - commands.ask / commands.deny appended verbatim; duplicates removed
 *   (first occurrence wins, order preserved).
 */
export function derivedPermissions(policy: ApprovalsPolicy): { ask: string[]; deny: string[] } {
  const ask: string[] = [];
  const deny: string[] = [];

  if (policy.approvals.force_push === "never") deny.push(...FORCE_PUSH_PATTERNS);
  else ask.push(...FORCE_PUSH_PATTERNS);

  // In integration mode the derived `Bash(gh pr merge*)` ask rule is
  // deliberately OMITTED: agents must be able to enable native auto-merge on
  // PRs targeting the integration branch, where green CI is the merge gate.
  // Merges to main stay human-gated SERVER-SIDE by the main ruleset's
  // required code-owner review, so dropping the client-side prompt loses
  // nothing there.
  if (policy.approvals.merge_to_main === "human") {
    // Guard direct pushes to the default branch. Derived from default_branch
    // so a non-`main` repo gets the right rule (never a stale `main` glob).
    const b = policy.branching.default_branch;
    ask.push(`Bash(git push origin ${b}*)`, `Bash(git push * ${b})`);
    // The client-side gh-pr-merge prompt is omitted in integration mode:
    // agents must enable native auto-merge on PRs into the integration branch
    // (green CI is the gate); main stays human-gated server-side by the
    // main ruleset's required code-owner review.
    if (policy.branching.mode !== "integration") ask.push("Bash(gh pr merge*)");
  }
  if (policy.approvals.deploy_production === "human") ask.push("Bash(gh workflow run *deploy*)");
  if (policy.approvals.release === "human") ask.push("Bash(npm publish*)", "Bash(gh release create*)");

  ask.push(...policy.commands.ask);
  deny.push(...policy.commands.deny);

  return { ask: dedupe(ask), deny: dedupe(deny) };
}

function dedupe(items: string[]): string[] {
  return [...new Set(items)];
}

/**
 * .claude/settings.json — the compiler owns permissions.ask and
 * permissions.deny ENTIRELY; everything else in an existing file (hooks,
 * other permissions keys, user config) is preserved. Personal additions
 * belong in settings.local.json.
 */
export function compileSettingsJson(policy: ApprovalsPolicy, existingText: string | null): string {
  const { ask, deny } = derivedPermissions(policy);
  let root: Record<string, unknown> = {};
  if (existingText !== null && existingText.trim() !== "") {
    let parsed: unknown;
    try {
      parsed = JSON.parse(existingText);
    } catch (err) {
      throw new CliError(
        `.claude/settings.json: invalid JSON — ${(err as Error).message}. Fix the file (or delete it) and rerun \`agentic approvals compile\`.`,
      );
    }
    if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
      throw new CliError(".claude/settings.json: top level must be a JSON object.");
    }
    root = { ...(parsed as Record<string, unknown>) };
  }
  const permissions =
    root.permissions !== null && typeof root.permissions === "object" && !Array.isArray(root.permissions)
      ? { ...(root.permissions as Record<string, unknown>) }
      : {};
  permissions.ask = ask;
  permissions.deny = deny;
  root.permissions = permissions;
  return JSON.stringify(root, null, 2) + "\n";
}

/**
 * scripts/copilot.sh — the repo-committed policy carrier for Copilot CLI.
 * Deny beats allow even under --allow-all, so the wrapper holds policy in
 * YOLO mode. Mapping: `Bash(<pattern>)` -> `--deny-tool 'shell(<pattern>)'`;
 * non-Bash entries pass through unchanged. Copilot has no "ask" tier, so ask
 * entries are ALSO denied here — a human runs those commands manually.
 */
export function compileCopilotWrapper(policy: ApprovalsPolicy): string {
  const { ask, deny } = derivedPermissions(policy);
  const lines: string[] = [
    "#!/usr/bin/env bash",
    `# ${GENERATED_HEADER}`,
    "#",
    "# Guarded GitHub Copilot CLI wrapper. Copilot has no repo-committed",
    "# permissions file, so this wrapper carries the approvals.yaml policy:",
    "# `--deny-tool` flags win over `--allow-all`, keeping the policy in force",
    "# even in fully autonomous runs.",
    "#",
    "# Mapping: an approvals entry `Bash(<pattern>)` becomes",
    "#   --deny-tool 'shell(<pattern>)'",
    "# (the Bash() wrapper is Claude syntax; Copilot's shell tool is `shell`).",
    "#",
    "# Copilot has no \"ask\" permission tier, so `commands.ask` entries are",
    "# ALSO denied below: the human owner runs those commands manually.",
    "set -euo pipefail",
    "",
    'exec copilot "$@" \\',
  ];
  const flags: string[] = [];
  for (const entry of deny) flags.push(denyFlag(entry));
  for (const entry of ask) {
    const f = denyFlag(entry);
    if (!flags.includes(f)) flags.push(f);
  }
  for (let i = 0; i < flags.length; i++) {
    lines.push(`  ${flags[i]}${i < flags.length - 1 ? " \\" : ""}`);
  }
  if (flags.length === 0) lines[lines.length - 1] = 'exec copilot "$@"';
  return lines.join("\n") + "\n";
}

function denyFlag(entry: string): string {
  const m = /^Bash\((.*)\)$/.exec(entry);
  const tool = m ? `shell(${m[1]})` : entry;
  return `--deny-tool '${tool.replace(/'/g, `'\\''`)}'`;
}

/** .github/CODEOWNERS — `* <owner>` when merge_to_main is human, plus one line per protected path. */
export function compileCodeowners(policy: ApprovalsPolicy): string {
  const lines: string[] = [`# ${GENERATED_HEADER}`, "#", "# Review ownership compiled from approvals.yaml."];
  if (policy.approvals.merge_to_main === "human") {
    lines.push(`* ${policy.owner}`);
  }
  for (const p of policy.protected_paths) {
    lines.push(`${p} ${policy.owner}`);
  }
  return lines.join("\n") + "\n";
}

/**
 * .github/rulesets/main-branch.json — importable GitHub branch ruleset
 * (Settings -> Rules -> Rulesets -> Import). JSON cannot carry a comment
 * header; `agentic approvals check` still detects drift.
 */
export function compileRuleset(policy: ApprovalsPolicy): string {
  const rules: unknown[] = [{ type: "deletion" }, { type: "non_fast_forward" }];
  if (policy.approvals.merge_to_main === "human") {
    rules.push({
      type: "pull_request",
      parameters: {
        required_approving_review_count: 1,
        dismiss_stale_reviews_on_push: false,
        require_code_owner_review: true,
        require_last_push_approval: false,
        required_review_thread_resolution: false,
        // In integration mode the release PR (dev -> main) must land as a
        // real merge commit (preserves per-task squash history + a release
        // point). Trunk mode leaves the method unrestricted.
        ...(policy.branching.mode === "integration"
          ? { allowed_merge_methods: [policy.branching.release_merge_method] }
          : {}),
      },
    });
  }
  rules.push({
    type: "required_status_checks",
    parameters: {
      strict_required_status_checks_policy: false,
      required_status_checks: [{ context: "gates-fast" }],
    },
  });
  const ruleset = {
    name: "main-branch",
    target: "branch",
    enforcement: "active",
    conditions: { ref_name: { include: [`refs/heads/${policy.branching.default_branch}`], exclude: [] } },
    rules,
    bypass_actors: [],
  };
  return JSON.stringify(ruleset, null, 2) + "\n";
}

export const INTEGRATION_RULESET_PATH = ".github/rulesets/integration-branch.json";

/**
 * .github/rulesets/integration-branch.json — compiled only when
 * branching.mode is "integration": an importable GitHub ruleset protecting
 * the integration branch. Deliberately NO pull_request/review rule — green
 * CI (`gates-fast`) is the merge gate for the integration branch (native
 * auto-merge); humans gate only main via the main-branch ruleset.
 */
export function compileIntegrationRuleset(policy: ApprovalsPolicy): string {
  const ruleset = {
    name: "integration-branch",
    target: "branch",
    enforcement: "active",
    conditions: { ref_name: { include: [`refs/heads/${policy.branching.integration_branch}`], exclude: [] } },
    rules: [
      { type: "deletion" },
      { type: "non_fast_forward" },
      {
        // Require a PR into the integration branch, but with ZERO required
        // reviews — green CI is the merge gate (auto-merge). The merge
        // method is pinned (default squash: dev stays linear, one commit
        // per task, which also keeps the rolling release diff readable).
        type: "pull_request",
        parameters: {
          required_approving_review_count: 0,
          dismiss_stale_reviews_on_push: false,
          require_code_owner_review: false,
          require_last_push_approval: false,
          required_review_thread_resolution: false,
          allowed_merge_methods: [policy.branching.integration_merge_method],
        },
      },
      {
        type: "required_status_checks",
        parameters: {
          strict_required_status_checks_policy: false,
          required_status_checks: [{ context: "gates-fast" }],
        },
      },
    ],
    bypass_actors: [],
  };
  return JSON.stringify(ruleset, null, 2) + "\n";
}

// ---------------------------------------------------------------------------
// compile / check
// ---------------------------------------------------------------------------

export interface CompiledSurface {
  /** Repo-relative path. */
  relPath: string;
  content: string;
  /** chmod applied on write (copilot.sh is 755). */
  mode?: number;
}

/**
 * Compile every enforcement surface in memory (settings merge uses the file
 * currently on disk). The list is mode-dependent: branching.mode
 * "integration" adds a fifth surface, the integration-branch ruleset.
 */
export function compileSurfaces(rootDir: string, policy: ApprovalsPolicy): CompiledSurface[] {
  const settingsPath = path.join(rootDir, ".claude", "settings.json");
  const surfaces: CompiledSurface[] = [
    { relPath: ".claude/settings.json", content: compileSettingsJson(policy, readTextIfExists(settingsPath)) },
    { relPath: "scripts/copilot.sh", content: compileCopilotWrapper(policy), mode: 0o755 },
    { relPath: ".github/CODEOWNERS", content: compileCodeowners(policy) },
    { relPath: ".github/rulesets/main-branch.json", content: compileRuleset(policy) },
  ];
  if (policy.branching.mode === "integration") {
    surfaces.push({ relPath: INTEGRATION_RULESET_PATH, content: compileIntegrationRuleset(policy) });
  }
  return surfaces;
}

/**
 * Write every surface for the current mode. In trunk mode a leftover
 * integration-branch ruleset (from a previous integration-mode compile) is
 * REMOVED, so flipping modes back cleans up. Returns the repo-relative paths
 * written.
 */
export function compileApprovals(rootDir: string, policy: ApprovalsPolicy): string[] {
  const written: string[] = [];
  for (const surface of compileSurfaces(rootDir, policy)) {
    const abs = path.join(rootDir, surface.relPath);
    ensureDir(path.dirname(abs));
    fs.writeFileSync(abs, surface.content);
    if (surface.mode !== undefined) fs.chmodSync(abs, surface.mode);
    written.push(surface.relPath);
  }
  if (policy.branching.mode !== "integration") {
    fs.rmSync(path.join(rootDir, INTEGRATION_RULESET_PATH), { force: true });
  }
  return written;
}

export interface DriftReport {
  ok: boolean;
  drifted: Array<{ path: string; reason: "missing" | "differs" | "stale" }>;
}

/**
 * Recompile in memory and diff against the files on disk. Missing generated
 * files count as drift; in trunk mode an EXISTING integration-branch ruleset
 * is drift too (reason "stale" — `approvals compile` removes it). Exit 1 on
 * any drift (CI runs this).
 */
export function checkApprovals(rootDir: string, policy: ApprovalsPolicy): DriftReport {
  const drifted: DriftReport["drifted"] = [];
  for (const surface of compileSurfaces(rootDir, policy)) {
    const onDisk = readTextIfExists(path.join(rootDir, surface.relPath));
    if (onDisk === null) drifted.push({ path: surface.relPath, reason: "missing" });
    else if (onDisk !== surface.content) drifted.push({ path: surface.relPath, reason: "differs" });
  }
  if (policy.branching.mode !== "integration" && fs.existsSync(path.join(rootDir, INTEGRATION_RULESET_PATH))) {
    drifted.push({ path: INTEGRATION_RULESET_PATH, reason: "stale" });
  }
  return { ok: drifted.length === 0, drifted };
}
