#!/usr/bin/env bash
# GENERATED by `agentic approvals compile` — edit approvals.yaml instead.
#
# Guarded GitHub Copilot CLI wrapper. Copilot has no repo-committed
# permissions file, so this wrapper carries the approvals.yaml policy:
# `--deny-tool` flags win over `--allow-all`, keeping the policy in force
# even in fully autonomous runs.
#
# Mapping: an approvals entry `Bash(<pattern>)` becomes
#   --deny-tool 'shell(<pattern>)'
# (the Bash() wrapper is Claude syntax; Copilot's shell tool is `shell`).
#
# Copilot has no "ask" permission tier, so `commands.ask` entries are
# ALSO denied below: the human owner runs those commands manually.
set -euo pipefail

exec copilot "$@" \
  --deny-tool 'shell(git push --force*)' \
  --deny-tool 'shell(git push -f*)' \
  --deny-tool 'shell(git reset --hard origin*)' \
  --deny-tool 'shell(git push origin main*)' \
  --deny-tool 'shell(git push * main)' \
  --deny-tool 'shell(gh pr merge*)' \
  --deny-tool 'shell(gh workflow run *deploy*)' \
  --deny-tool 'shell(npm publish*)' \
  --deny-tool 'shell(gh release create*)'
