#!/usr/bin/env bash
# GENERATED by `agentic approvals compile` (harness v0.2.1) — edit approvals.yaml instead.
#
# Guarded GitHub Copilot CLI wrapper — a FALLBACK policy carrier kept for
# defense in depth. The PRIMARY carrier is the native repo-committed hooks
# surface Copilot reads automatically: .github/hooks/copilot-cli-policy.json
# + scripts/hooks/copilot-policy.mjs (which also implements a real "ask"
# tier via the preToolUse hook's ask decision). This wrapper's
# `--deny-tool` flags win over `--allow-all`, keeping the policy in force
# even in fully autonomous runs, if something invokes `copilot` directly.
#
# Mapping: an approvals entry `Bash(<pattern>)` becomes
#   --deny-tool 'shell(<pattern>)'
# (the Bash() wrapper is Claude syntax; Copilot's shell tool is `shell`).
#
# `--deny-tool` has no "ask" concept, so `commands.ask` entries are ALSO
# denied below — the native hooks surface above is where ask actually asks.
set -euo pipefail

exec copilot "$@" \
  --deny-tool 'shell(git push --force*)' \
  --deny-tool 'shell(git push -f*)' \
  --deny-tool 'shell(git reset --hard origin*)' \
  --deny-tool 'shell(git push origin main*)' \
  --deny-tool 'shell(git push * main)' \
  --deny-tool 'shell(gh pr merge*)' \
  --deny-tool 'shell(gh workflow run *deploy*)' \
  --deny-tool 'shell(npm publish*)' \
  --deny-tool 'shell(gh release create*)'
