#!/usr/bin/env node
// GENERATED by `agentic approvals compile` (harness v0.2.0) — edit approvals.yaml instead.
//
// preToolUse command hook for GitHub Copilot CLI's native repo-committed
// hooks format (.github/hooks/*.json), registered by
// .github/hooks/copilot-cli-policy.json. Schema + format per GitHub Docs
// (fetched 2026-07-24):
//   https://docs.github.com/en/copilot/reference/hooks-reference
//   https://docs.github.com/en/copilot/tutorials/copilot-cli-hooks
// preToolUse hooks receive {sessionId,timestamp,cwd,toolName,toolArgs} JSON
// on stdin and must print {"permissionDecision":"allow"|"deny"|"ask"} on
// stdout with exit 0 -- a crash or non-zero exit is FAIL-CLOSED (denies the
// call even if stdout said allow), so every path below always exits 0.
// Unlike scripts/copilot.sh's --deny-tool (no ask concept -- ask folds into
// deny there), this hook can return a real "ask" decision, so Copilot now
// gets the same ask/deny distinction Claude's settings.json permissions do.
//
// Mapping (same derivedPermissions() source as .claude/settings.json and
// scripts/copilot.sh): `Bash(<pattern>)` becomes a whole-string wildcard
// match against the bash/powershell tool's `command` argument.
// protected_paths globs are matched against edit/create/str_replace_editor/
// apply_patch file arguments -- the field name holding the path is
// undocumented upstream, so path/file_path/filePath are all tried.
// Human override for a supervised protected-path edit (same marker as
// scripts/hooks/protect-policy.mjs): touch .agents/.cache/policy-edit-ok

import { existsSync, readFileSync } from "node:fs";
import { resolve, relative, isAbsolute, sep, dirname } from "node:path";

const DENY_PATTERNS = ["git push --force*","git push -f*","git reset --hard origin*"];
const ASK_PATTERNS = ["git push origin main*","git push * main","gh pr merge*","gh workflow run *deploy*","npm publish*","gh release create*"];
const PROTECTED_PATTERNS = ["tests/**",".agentic/harness/tests/**",".github/workflows/**","approvals.yaml","agentic.config.json",".claude/settings.json"];

const BASH_TOOLS = new Set(["bash", "powershell"]);
const FILE_TOOLS = new Set(["edit", "create", "str_replace_editor", "apply_patch"]);

function wildcardToRegExp(pattern) {
  const escaped = pattern.replace(/[\\^$.|?+()[\]{}]/g, "\\$&").replace(/\*/g, ".*");
  return new RegExp("^" + escaped + "$");
}

// Same minimal glob as scripts/hooks/protect-policy.mjs: "**" crosses
// directories, "*" does not.
function pathGlobToRegExp(pattern) {
  let re = "";
  for (let i = 0; i < pattern.length; i++) {
    const c = pattern[i];
    if (c === "*") {
      if (pattern[i + 1] === "*") {
        re += ".*";
        i++;
        if (pattern[i + 1] === "/") i++;
      } else {
        re += "[^/]*";
      }
    } else if ("\\^$.|?+()[]{}".includes(c)) {
      re += "\\" + c;
    } else {
      re += c;
    }
  }
  return new RegExp("^(?:" + re + ")$");
}

function isProtectedPath(relPath) {
  return PROTECTED_PATTERNS.some((p) => {
    if (pathGlobToRegExp(p).test(relPath)) return true;
    if (p.endsWith("/**") && relPath === p.slice(0, -3)) return true;
    return false;
  });
}

function findRepoRoot(startDir) {
  let dir = resolve(startDir);
  for (let i = 0; i < 64; i++) {
    if (existsSync(resolve(dir, "approvals.yaml")) || existsSync(resolve(dir, "agentic.config.json"))) {
      return dir;
    }
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return resolve(startDir);
}

function normalizeArgs(toolArgs) {
  if (typeof toolArgs === "string") {
    try {
      return JSON.parse(toolArgs);
    } catch {
      return {};
    }
  }
  return toolArgs && typeof toolArgs === "object" ? toolArgs : {};
}

function allow() {
  return { permissionDecision: "allow" };
}

function decide(input) {
  const toolName = typeof input.toolName === "string" ? input.toolName : "";
  const args = normalizeArgs(input.toolArgs);

  if (BASH_TOOLS.has(toolName) && typeof args.command === "string") {
    const command = args.command;
    if (DENY_PATTERNS.some((p) => wildcardToRegExp(p).test(command))) {
      return {
        permissionDecision: "deny",
        permissionDecisionReason: "Denied by approvals.yaml commands.deny -- a human runs this manually.",
      };
    }
    if (ASK_PATTERNS.some((p) => wildcardToRegExp(p).test(command))) {
      return {
        permissionDecision: "ask",
        permissionDecisionReason: "approvals.yaml requires human approval for this command.",
      };
    }
    return allow();
  }

  if (FILE_TOOLS.has(toolName)) {
    const target = args.path ?? args.file_path ?? args.filePath;
    if (typeof target === "string") {
      const startDir = typeof input.cwd === "string" ? input.cwd : process.cwd();
      const repoRoot = findRepoRoot(startDir);
      const abs = isAbsolute(target) ? target : resolve(repoRoot, target);
      let rel = relative(repoRoot, abs).split(sep).join("/");
      if (rel.startsWith("..")) rel = abs.split(sep).join("/");
      if (isProtectedPath(rel) && !existsSync(resolve(repoRoot, ".agents/.cache/policy-edit-ok"))) {
        return {
          permissionDecision: "deny",
          permissionDecisionReason:
            rel +
            " is an owner-approval file (approvals.yaml protected_paths) -- do not edit it unless your task explicitly says so; a human can permit a supervised edit with: touch .agents/.cache/policy-edit-ok",
        };
      }
    }
  }

  return allow();
}

function readStdin() {
  try {
    return readFileSync(0, "utf8");
  } catch {
    return "";
  }
}

try {
  const raw = readStdin();
  const input = raw.trim() ? JSON.parse(raw) : {};
  process.stdout.write(JSON.stringify(decide(input)) + "\n");
  process.exit(0);
} catch (err) {
  process.stderr.write("copilot-policy hook error (allowing): " + (err && err.message ? err.message : err) + "\n");
  process.stdout.write(JSON.stringify({ permissionDecision: "allow" }) + "\n");
  process.exit(0);
}
